Feature/clase sin detalle
udistrital/catalogo_elementos_crud pull request #82
Opened 2021-09-20 08:00 UTC by ludwinggsanchez

Relacionado a udistrital/arka_cliente#787

2021-09-20 13:11 UTC, AlexFBP requested changes
Campos DateTime
- Bien sea `with timezone`
- O bien siempre guardados con zona UTC

2021-09-20 13:11 UTC, AlexFBP commented on models/detalle_subgrupo.go
> +	FechaModificacion time.Time `orm:"auto_now;column(fecha_modificacion);type(timestamp without time zone)"`
Si no vamos a usar time_bogotá, los campos deberían ser `with timezone`

2021-09-22 06:53 UTC, ludwinggsanchez commented
Se resuelve la gestión de fechas de creación y modificación mediante una función y un trigger asociado a cada tabla. Es fácil de extender a los demás apis.

2021-09-22 16:00 UTC, AlexFBP requested changes
Los únicos cambios necesarios son respecto a `models/tr_grupo.go`. Los demás comentarios (en `models/catalogo.go`)son cosas a preguntar al cliente

De resto todo se ve bien, está bueno el aporte de los trigger

2021-09-22 16:00 UTC, AlexFBP commented on models/catalogo.go
> +	FechaFin          string    `orm:"column(fecha_fin);type(timestamp without time zone);null"`
Pendiente por confirmar con Cliente y/o Analista si estos campos tienen sentido para el catálogo (y en general, revisarlos). De ser necesarios, también deberían ser `with time zone`

2021-09-22 16:00 UTC, AlexFBP commented on models/catalogo.go
> +		m.FechaFin = v.FechaFin
Pregunta: Aún con los trigger, esto es necesario?

2021-09-22 16:00 UTC, AlexFBP commented on models/tr_grupo.go
> +		                }*/
Eliminar (o mandar a una rama o stash), total ya hace parte de la historia y se podría consultar con Git
Si se ha de mantener, colocar un comentario que indique el por qué

2021-09-22 16:00 UTC, AlexFBP commented on models/tr_grupo.go
> +	//	w := m.DetalleSubgrupo
Eliminar (o mandar a una rama o stash), total ya hace parte de la historia y se podría consultar con Git
Si se ha de mantener, colocar un comentario que indique el por qué

2021-09-23 03:13 UTC, ludwinggsanchez commented on models/catalogo.go
> +		m.FechaFin = v.FechaFin
Si señor, los triggers están hechos para las columnas fecha_creacion y fecha_modificacion

2021-09-23 03:14 UTC, ludwinggsanchez commented on models/catalogo.go
> +	FechaFin          string    `orm:"column(fecha_fin);type(timestamp without time zone);null"`
Listo, hagamos el ajuste una vez confirmado con el usuario,

2021-09-23 04:26 UTC, AlexFBP approved these changes

2021-09-23 04:26 UTC, merged