Feature/parametrizacion tipos bien
udistrital/catalogo_elementos_crud pull request #85
Opened 2021-10-05 21:31 UTC by CristianDavidSanchez

#84 Actualización del modelo y pruebas de los metodos para parametrizacion en arka cliente

2021-10-05 21:45 UTC, AlexFBP requested changes

2021-10-05 21:45 UTC, AlexFBP commented on models/tipo_bien.go
> +	Reglas            int       `orm:"column(reglas);null"`
Revisar el tipo de dato de `Reglas`. Según parece es no mas `string`, y hay que colocarle `type(jsonb)`

Ver [documentación de Beego](https://beego.me/docs/mvc/model/models.md#postgresql) para más información

2021-10-05 21:53 UTC, AlexFBP commented on models/tipo_bien.go
> +	Tipo_bien_padre   int       `orm:"column(tipo_bien_padre);null"`
- El tipo de dato de pronto no es `int` sino `*TipoBien`
- Para que lo anterior funcione, faltaría agregar la [propiedad orm](https://beego.me/docs/mvc/model/models.md#one-to-many) para el tipo de relación, posiblemente sea agregar `rel(fk_tipo_bien_tipo_bien_padre)`

2021-10-07 15:49 UTC, CristianDavidSanchez commented on models/tipo_bien.go
> +	Tipo_bien_padre   int       `orm:"column(tipo_bien_padre);null"`
Cambios realizados @AlexFBP

2021-10-08 08:34 UTC, AlexFBP approved these changes

2021-10-08 09:04 UTC, merged